# Generated by Django 4.2.18 on 2025-05-22 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_permiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignarPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permisos', models.ManyToManyField(related_name='roles_asignados', to='app.permiso')),
                ('rol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_asignados', to='app.rol')),
            ],
            options={
                'verbose_name': 'Asignación de Permisos',
                'verbose_name_plural': 'Asignaciones de Permisos',
            },
        ),
    ]
