# Generated by Django 4.2.18 on 2025-05-22 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=10),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('domicilio', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('dui', models.CharField(max_length=10, unique=True)),
                ('nit', models.CharField(max_length=17, unique=True)),
                ('seguro', models.CharField(blank=True, max_length=20, null=True)),
                ('afp', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=10)),
                ('tipo_pago', models.CharField(choices=[('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('SEMANAL', 'Semanal')], max_length=10)),
                ('eventual', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('tipo_cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cargo')),
            ],
        ),
    ]
