# Generated by Django 4.2.18 on 2025-05-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cargo_comentarios_alter_cargo_estado_empleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='distrito',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dui',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='municipio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nacionalidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nit',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
