# Generated by Django 4.2.18 on 2025-05-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_empleado_options_alter_empleado_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='distrito',
        ),
    ]
