# Generated by Django 4.2.18 on 2025-05-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_empleado_distrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='nit',
        ),
    ]
