# Generated by Django 4.2.18 on 2025-05-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_empleado_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='nit',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
