# Generated by Django 4.2.18 on 2025-05-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_empleado_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de Permiso',
                'verbose_name_plural': 'Tipos de Permiso',
            },
        ),
    ]
