# Generated by Django 4.2.18 on 2025-05-23 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_tipopermiso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'verbose_name': 'Admin Permiso', 'verbose_name_plural': 'Admin Permisos'},
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('remuneracion', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='app.empleado')),
                ('tipo_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='app.tipopermiso')),
            ],
            options={
                'verbose_name': 'Permisos',
                'verbose_name_plural': 'Permisos',
            },
        ),
    ]
